# -*- coding: utf-8 -*-
"""data cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPcn_frdFjio993yxaQ0loReHNyDxqlh
"""

import pandas as pd

data = pd.read_csv('europe-motorbikes-zenrows.csv')
data.info()

data = data.drop_duplicates()
data.info()

data.head(20)

data = data.drop('version', axis=1)
data = data.drop('link', axis=1)

data

data['date'] = data['date'].replace({'\d{1,2}\/':''},regex=True)
data = data.rename(columns={'date': 'year'})
data

data.info()

data['power'].fillna('0', inplace=True)

data.fillna('NULL', inplace=True)

data

data = data.to_csv('motorbikes-sales.csv', index = True)